image: Visual Studio 2017

branches:
  only:
    - master

version: "Build {build}"

skip_tags: false

skip_commits:
  files:
    - images/
    - src/
    - .gitignore
    - LICENSE
    - README.md

environment:
  PsgKey:
    secure: tlhLuUS6x8FcP159+X/EIBDlj9m+u5KCTTuqwzsiNHlPX6K4AolpaZcfAP4ClOdB
  matrix:
    - DOCKER_IMAGE:
    - DOCKER_IMAGE: nanoserver
    - DOCKER_IMAGE: windowsservercore

cache:
  - test\download-cache -> .appveyor.yml
  - '%ProgramFiles%\WindowsPowerShell\Modules\VcRedist -> .appveyor.yml'
  - '%ProgramFiles%\WindowsPowerShell\Modules\PSScriptAnalyzer -> .appveyor.yml'
  - '%ProgramFiles%\WindowsPowerShell\Modules\Pester -> .appveyor.yml'

build: off

install:
  - ps: |
      if ($null -eq $Env:DOCKER_IMAGE -or $Env:DOCKER_IMAGE -eq '') {
        .\test\setup.ps1
      } else {
        & ".\test\Dockerfile.$Env:DOCKER_IMAGE.ps1"
      }

test_script:
  - ps: |
      if ($null -eq $Env:DOCKER_IMAGE -or $Env:DOCKER_IMAGE -eq '') {
        $pesterResult = .\test\pester.ps1
        $failCount = $pesterResult.FailedCount
      } else {
        $volume="$($Env:APPVEYOR_BUILD_FOLDER):C:\App"
        docker run --rm --volume $volume --workdir C:\App --env "PM_TEST_DOCKER=1" phpmanager/test powershell.exe 'Set-Location -LiteralPath C:\App; $pesterResult=.\test\pester.ps1; exit $pesterResult.FailedCount'
        $failCount = $LASTEXITCODE
      }
      (New-Object 'System.Net.WebClient').UploadFile("https://ci.appveyor.com/api/testresults/nunit/$($env:APPVEYOR_JOB_ID)", (Resolve-Path -LiteralPath .\TestsResults.xml))
      if ($failCount -ne 0) {
        throw "$failCount tests failed!"
      }

deploy_script:
  - ps: |
      if (($null -eq $Env:DOCKER_IMAGE -or $Env:DOCKER_IMAGE -eq '') -and $true -eq $Env:APPVEYOR_REPO_TAG -and $Env:APPVEYOR_REPO_TAG_NAME -match '^\d+\.\d+\.\d+$') {
        $newVersion = $Env:APPVEYOR_REPO_TAG_NAME + '.' + $Env:APPVEYOR_BUILD_NUMBER
        Write-Host "Publishing new version: $newVersion"
        $releaseNotes = ''
        $tags = @(& git tag --list --sort=-version:refname)
        if ($tags.Count -lt 2) {
          Write-Host 'Less than 2 tags found: empty release notes'
        } else {
          $thisTagIndex = [array]::IndexOf($tags, $Env:APPVEYOR_REPO_TAG_NAME)
          if ($thisTagIndex -lt 0) {
            Write-Host 'Unable to find the index of the current tag: empty release notes'
          }
          $previousTag = ''
          for ($tagIndex = $thisTagIndex + 1; $tagIndex -lt $tags.Count; $tagIndex++) {
            if ($tags[$tagIndex] -match '^\d+\.\d+\.\d+$') {
              $previousTag = $tags[$tagIndex]
              break
            }
          }
          if ($previousTag -eq '') {
            Write-Host 'Unable to find the previously published tag: empty release notes'
          } else {
            $rawCommitMessages = @(& git log --format='- %s' --no-merges --reverse ("$previousTag..." + $Env:APPVEYOR_REPO_TAG_NAME) -- .\PhpManager)
            $commitMessages = @()
            foreach ($rawCommitMessage in $rawCommitMessages) {
              if (-Not($rawCommitMessage -imatch '^- \[minor\]')) {
                $commitMessages += $rawCommitMessage
              }
            }
            if ($commitMessages.Count -lt 1) {
              Write-Host 'No relevant commit messages found: empty release notes'
            } else {
              $releaseNotes = [string]::Join("`n", $commitMessages)
              Write-Host "Release notes:`n$releaseNotes"
            }
          }
        }
        Update-ModuleManifest -Path .\PhpManager\PhpManager.psd1 -ModuleVersion $newVersion -ReleaseNotes $releaseNotes
        Import-Module -Force .\PhpManager
        Publish-Module -Repository PSGallery -Path .\PhpManager -NuGetApiKey $Env:PsgKey -Force
      }
